### ISSUE TITLE
boom clock didn't change on vcd

### ISSUE THREAD

**Issue by albertethon** [circt/arc-tests#5]
I attempted to simulate with `make run-trace` in Boom and tried to observe the vcd file using Gtkwave. However, I noticed that the clock signal remained unchanged. Could you please advise on the possible reasons for this?

## To Reproduce
1. `cd boom && make run-trace`
2. `cd build/small`
3. `gtkwave boom-arcs.vcd`

![boom-arcs-vcd](https://github.com/circt/arc-tests/assets/41829940/ad9a55d4-c854-480b-bc5f-95e6be15e191)

**Comment by fabianschuiki** [comment]
I think this is because we are only writing the signals to the VCD file once per clock cycle: https://github.com/circt/arc-tests/blob/241042eead2ceb529ac600aad686721b840d7d8e/boom/boom-main.cpp#L52. If you add another VCD call when the clock is low, you should see the clock toggling as expected. You may need to adjust the `cycles` time passed to the VCD dump, something like `2*cycles+0` for the first and `2*cycles+1` for the second call.
